requires 'Archive::Zip', '0.11';
requires 'BSD::Resource';
requires 'Carp';
requires 'Compress::Zlib', '1.14';
requires 'Digest::MD5';
requires 'DynaLoader';
requires 'Fcntl';
requires 'File::ShareDir::ProjectDistDir', '0.1.1';
requires 'File::Sync';
requires 'File::Temp';
requires 'Getopt::Long';
requires 'IO', '1.25';
requires 'IO::Scalar';
requires 'IO::Socket::SSL', '1.09';
requires 'Net::FTP';
requires 'POSIX';
requires 'Socket';
requires 'Sys::Hostname';
requires 'Sys::Syslog';
